services:
  - type: web
    name: shopify-internal-notes-app
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: starter
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
      - key: SCOPES
        value: read_products,write_products,read_orders,write_orders
      - key: DATABASE_URL
        fromDatabase:
          name: internal-notes-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: S3_BUCKET_NAME
        sync: false

databases:
  - name: internal-notes-db
    databaseName: internal_notes_app
    user: internal_notes_user
    plan: starter