api_version = "2025-07"

[[extensions]]
type = "ui_extension"
name = "Order Fulfillment Notes"
handle = "order-fulfillment-notes"

[[extensions.targeting]]
target = "admin.order-details.block.render"
module = "./src/OrderDetailsBlock.tsx"