api_version = "2024-01"

[[extensions]]
type = "ui_extension"
name = "Product Notes"
handle = "product-notes"

[[extensions.targeting]]
target = "admin.product-details.block.render"
module = "./src/ProductNotesBlock.tsx"

[[extensions.targeting]]
target = "admin.product-details.action.render"
module = "./src/ProductNotesAction.tsx"