api_version = "2025-07"

[[extensions]]
type = "ui_extension"
name = "Product Notes"
handle = "product-notes"

[[extensions.targeting]]
target = "admin.product-details.block.render"
module = "./src/ProductNotesBlock.tsx"